### ISSUE TITLE
Organização do Repo

### ISSUE THREAD

**Issue by heliohead** [vim-sp/vim-sp#1]
Melhor nós centralizarmos as idéias aqui ;)
@matmarsiglio , @woliveiras

**Comment by woliveiras** [comment]
Maravilha :smile:

**Comment by heliohead** [comment]
o Mateus sugeriu uma estrutura igual [esta](https://github.com/raphaelfabeni/css-sp), eu acho legal ter uma pasta para cada evento para podermos tem comentários por meetup.

**Comment by woliveiras** [comment]
Assim é show de bola! O esquema do [previous](https://github.com/vim-sp/vim-sp/tree/master/previous) seria pra fazer algo desse tipo, ai movi a pasta 1-meetup. Seria legal então ter um .md pra cada Meetup e colocar somente as infos né?

**Comment by mtmr0x** [comment]
@woliveiras eu acho assim legal, que podemos centralizar tudo num unico documento para cada edição. Fora que é fácil de achar.

**Comment by mtmr0x** [comment]
@woliveiras @heliohead mas eu achei tbm o nome da pasta como "Previous" mais interessante e que faz mais sentido.

**Comment by mtmr0x** [comment]
@woliveiras @heliohead Estou terminando umas estruturação legal aqui e vou abrir um PR. Queria que vocês olhassem e discutissimos pra ver se é um bom caminho :)

**Comment by woliveiras** [comment]
Show @matmarsiglio

**Comment by mtmr0x** [comment]
@woliveiras @heliohead https://github.com/vim-sp/vim-sp/pull/2

Olhem tudo, please :smile:

**Comment by mtmr0x** [comment]
Acho que já podemos fechar essa issue tbm, não?

**Comment by woliveiras** [comment]
Creio que sim ein

**Comment by heliohead** [comment]
Movi os relatos para a pasta do meetup correspondent #3 

Dá uma olhada
