### ISSUE TITLE
Cursos e HOW-TO

### ISSUE THREAD

**Issue by evansantos** [vim-sp/vim-sp#4]
Vocês tem algum link para compartilhar coisas para quem é novato ou até experientes no vim ? 

Eu vi que no EggHead tá free esse curso: 
[Learn to Use VIM](https://egghead.io/series/learn-to-use-vim)

![news-atl-down-MTclfCr4tVgis](https://camo.githubusercontent.com/4d3cd1ddfffe47b0ab4028171dd6bb0642e286d7/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f4d54636c6643723474566769732f67697068792e676966)

**Comment by woliveiras** [comment]
Ooooopa, aqui:
- https://www.gitbook.com/book/cassiobotaro/vimbook/details
- https://github.com/matteocrippa/awesome-vim
- https://github.com/mhinz/vim-galore
- http://woliveiras.com.br/vimparanoobs/

**Comment by heliohead** [comment]
Vamos criar uma sessão no repo para isso :) 👍

**Comment by heliohead** [comment]
@evansantos te inclui como membro faz um fork e pull request :)

**Comment by evansantos** [comment]
@heliohead beleza :D

**Comment by felipeorlando** [comment]
Conteúdo pra aprendizado é o que mais tem. rs
As 4 da matina não consigo lembrar de muitos, mas de 'bate bola, jogo rápido' tem o do Laracasts (https://laracasts.com/series/vim-mastery). 😄

**Comment by felipeorlando** [comment]
Inclusive, como VIM acaba sendo um mistério pra muita galera, seria interessante ter o awesome vim (https://github.com/mhinz/vim-galore) em pt-BR. Ao menos um overview dele. 👍

**Comment by evansantos** [comment]
Estou fechando a Issue visando que já foi feito o merge
