### ISSUE TITLE
Meetup ;)

### ISSUE THREAD

**Issue by juliodias** [vim-sp/vim-sp#9]
Olá pessoal, tudo bem com voces?
Tem alguma possibilidade de movimentarmos esse meetup novamente?

**Comment by heliohead** [comment]
Fala Julio,

Teve um segundo meetup, tinha perto de 30 confirmados, depois de arrumar um espaço, comprei o café da manhã do meu bolso para 30 pessoas, foram 3, os palestrantes também furaram ai eu desanimei.

Se você quiser tocar o barco, a casa é sua 😎

**Comment by juliodias** [comment]
Opa Helio,

Vou correr atrás disso, movimentar os repositórios e tentar fazer as coisas acontecerem. Peco sua ajuda também haha
Consigo me tornar um membro também?

Abraco @heliohead

**Comment by heliohead** [comment]
Te coloquei como admin antes de reponder aqui :)
![Screenshot 2019-05-16 10 04 48](https://user-images.githubusercontent.com/675604/57855948-46ff2d80-77c2-11e9-95ef-ae416404d699.png)

So precisa aceitar 😎
